INCLUDES =	containers/Vector.hpp\
			containers/Stack.hpp\
			iterators/iterator_traits.hpp\
			iterators/RandomAccessIterator.hpp\
			iterators/ReverseIterator.hpp\
			tools/tools.hpp\
			tools/type_traits.hpp\
			ft_tester/includes/main.hpp

INCLUDES_STL =	stl_tester/includes/main.hpp

NAME = ft_containers

NAME_STL = stl_containers

CC = clang++

FLAGS = -Wall -Wextra -Werror -std=c++98

.cpp.o:
		$(CC) -g3 $(FLAGS) -c $< -o $(<:.cpp=.o)

$(NAME):	

all :	

clean :
		

fclean : clean
		

re :	fclean all
